defaults:
  outputFramesDirectory: "./data/frames"
  clipFilePath: "./data/video/clip.mp4"
  clipFileName: "clip.mp4"

bufferSettings:
  size: 10

playback:
  frameDelay: 42

debugging:
  debug: True
